version: '3.4'

# Pour démarrer ces containeurs, aller dans le répertoire du docker-compose wikibase et lancer :
# docker-compose -f docker-compose.yml -f ../pilote-fne/src/main/docker/docker-compose.yml up -d

services:

#  pilote-fne:
#    build:
#      context: .
#      dockerfile: DockerFile
#    container_name: pilote-fne-container
#    ports:
#      - "8080:8080"
#    networks:
#      default:
#        aliases:
#          - pilote-fne.svc

  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus-container
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      default:
        aliases:
          - prometheus.svc

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter-container
    links:
      - mysql
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "root:my-secret-pw@(mysql:3306)/my_wiki"
    ports:
      - "9104:9104"
    networks:
      default:
        aliases:
          - mysqld-exporter.svc

  grafana:
    image: grafana/grafana-oss:9.1.4
    container_name: grafana-container
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      default:
        aliases:
          - grafana.svc
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
